### ISSUE TITLE
Array.prototype.find under IE

### ISSUE THREAD

**Issue by liuyuchenzh** [Chimeejs/chimee-helper-events#1]
https://github.com/Chimeejs/chimee-helper-events/blob/3e2676d80ae34bd84c340eb565f09a201e44316a/src/index.js#L110

Using Array.prototype.find here but seems like no polyfill included, which could cause err under IE : )

**Comment by toxic-johann** [comment]
You should use [babel-polyfill](https://babeljs.io/docs/usage/polyfill/) by yourself if you want to run it under IE.

**Comment by liuyuchenzh** [comment]
Then what about some tip or notice in README? Would be nice

**Comment by toxic-johann** [comment]
hmmm, I agree with you.

**Comment by toxic-johann** [comment]
@liuyuchenzh Which one are you using,  chimee-helper-events, chimee or chimee-player?

**Comment by liuyuchenzh** [comment]
@toxic-johann Currently chimee-player
